language: node_js
node_js:
  - "8"
services:
  - docker
env:
  matrix:
  - VERSION=1.0.0-alpha
script:
 - npm run build
 - docker build . -t claudiotx/7a7186a:"$VERSION"
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master